//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEventosEntities : DbContext
    {
        public dbEventosEntities()
            : base("name=dbEventosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCiudades> tbCiudades { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbEventoDetalle> tbEventoDetalle { get; set; }
        public virtual DbSet<tbEventos> tbEventos { get; set; }
        public virtual DbSet<tbOcupaciones> tbOcupaciones { get; set; }
        public virtual DbSet<tbParticipantes> tbParticipantes { get; set; }
        public virtual DbSet<tbTiposEventos> tbTiposEventos { get; set; }
        public virtual DbSet<tbUsuaios> tbUsuaios { get; set; }
    }
}
