//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDepartamentos()
        {
            this.tbCiudades = new HashSet<tbCiudades>();
        }
    
        public int dep_Id { get; set; }
        public string dep_descripcion { get; set; }
        public Nullable<bool> dep_Estado { get; set; }
        public Nullable<int> usu_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dep_FechaCreacion { get; set; }
        public Nullable<int> usu_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> dep_FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCiudades> tbCiudades { get; set; }
        public virtual tbUsuaios tbUsuaios { get; set; }
        public virtual tbUsuaios tbUsuaios1 { get; set; }
    }
}
