//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEmpleados()
        {
            this.tbEventos = new HashSet<tbEventos>();
            this.tbUsuaios2 = new HashSet<tbUsuaios>();
        }
    
        public int emp_Id { get; set; }
        public string emp_PrimerNombre { get; set; }
        public string emp_SegundoNombre { get; set; }
        public string emp_PrimerApellido { get; set; }
        public string emp_SegundoApellido { get; set; }
        public string emp_Sexo { get; set; }
        public System.DateTime emp_FechaNacimiento { get; set; }
        public int estad_Id { get; set; }
        public int ciu_Id { get; set; }
        public string emp_Direccion { get; set; }
        public string emp_Telefono { get; set; }
        public Nullable<int> ocu_Id { get; set; }
        public Nullable<bool> emp_Estado { get; set; }
        public Nullable<int> usu_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> emp_FechaCreacion { get; set; }
        public Nullable<int> usu_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> emp_FechaModificacion { get; set; }
    
        public virtual tbCiudades tbCiudades { get; set; }
        public virtual tbOcupaciones tbOcupaciones { get; set; }
        public virtual tbEstadosCiviles tbEstadosCiviles { get; set; }
        public virtual tbUsuaios tbUsuaios { get; set; }
        public virtual tbUsuaios tbUsuaios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEventos> tbEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuaios> tbUsuaios2 { get; set; }
    }
}
