//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEventos()
        {
            this.tbEventoDetalle = new HashSet<tbEventoDetalle>();
        }
    
        public int event_Id { get; set; }
        public string event_Nombre { get; set; }
        public Nullable<int> ciu_Id { get; set; }
        public Nullable<int> tipoE_Id { get; set; }
        public Nullable<System.DateTime> event_Fecha { get; set; }
        public Nullable<System.TimeSpan> event_Hora { get; set; }
        public Nullable<decimal> event_Presupuesto { get; set; }
        public Nullable<int> emp_Id { get; set; }
        public Nullable<bool> event_Estado { get; set; }
        public Nullable<int> usu_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> event_FechaCreacion { get; set; }
        public Nullable<int> usu_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> event_FechaModificacion { get; set; }
    
        public virtual tbCiudades tbCiudades { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEventoDetalle> tbEventoDetalle { get; set; }
        public virtual tbTiposEventos tbTiposEventos { get; set; }
        public virtual tbUsuaios tbUsuaios { get; set; }
        public virtual tbUsuaios tbUsuaios1 { get; set; }
    }
}
