//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEventoDetalle
    {
        public int evde_Id { get; set; }
        public Nullable<int> par_Id { get; set; }
        public Nullable<int> event_Id { get; set; }
        public Nullable<bool> evde_Estado { get; set; }
        public Nullable<int> usu_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> evde_FechaCreacion { get; set; }
        public Nullable<int> usu_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> evde_FechaModificacion { get; set; }
    
        public virtual tbEventos tbEventos { get; set; }
        public virtual tbUsuaios tbUsuaios { get; set; }
        public virtual tbUsuaios tbUsuaios1 { get; set; }
        public virtual tbParticipantes tbParticipantes { get; set; }
    }
}
