//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTiposEventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTiposEventos()
        {
            this.tbEventos = new HashSet<tbEventos>();
        }
    
        public int tipoE_Id { get; set; }
        public string tipoE_Descripcion { get; set; }
        public Nullable<bool> tipoE_Estado { get; set; }
        public Nullable<int> usu_UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> tipoE_FechaCreacion { get; set; }
        public Nullable<int> usu_UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> tipoE_FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEventos> tbEventos { get; set; }
        public virtual tbUsuaios tbUsuaios { get; set; }
        public virtual tbUsuaios tbUsuaios1 { get; set; }
    }
}
